global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: ecoflow
    static_configs:
      - targets:
          - ecoflowexporter:9090

  - job_name: nws_exporter
    static_configs:
      - targets:
          - nwsexporter:8080
    scrape_interval: 60s
